# Generated by Django 5.0.1 on 2024-01-08 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('image_name', models.CharField(max_length=100)),
            ],
        ),
    ]
