# Generated by Django 5.0.1 on 2024-01-12 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_image_name_post_file_name_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 12, 0, 6, 25, 646917, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
